#!/bin/bash

# based upon 'qemu' from
# 12/2010 Matthias Henze
# Lizenz: GPL v2
#
# updated for libvirtd (virsh) by
# Jonathan Mills 09/2011
#
# updated by
# Christian Burmeister 05/2015
#
# updated by
# deepestblue2008 04/2021
#


if which virsh >/dev/null; then
    echo '<<<qemu>>>'
    virsh list | grep -v 'State' | grep -v '^--' | grep -v '^$' | while read L
    do
            ID=$(echo $L | awk '{print $1}')
            NAME=$(echo $L | awk '{print $2}')
            STATE=$(echo $L | awk '{print $3}')
            MEM=$(virsh dominfo $NAME | grep 'Used memory' | awk '{print $3}')
            let MEM=MEM/1024

            # qemu -> CentOS     libvirt+ -> Ubuntu
            QEMU_VER=$(ps aux | grep -enable-kvm | grep -v grep | head -1 | awk -- '{print $1}')

            # kvm on CentOS
            if [ $QEMU_VER = "qemu" ]; then
                    PID=$(ps aux | grep kvm | grep $NAME" " | grep -v grep | awk '{print $2}')
                    if [ $PID -gt 0 ]; then
                            DATA=$(top -p $PID -n 1 -b | tail -2 | head -1 | awk -- '{print $9" "$10}')
                    else
                            DATA=""
                    fi

            else

            # kvm on Ubuntu
                    PID=$(ps aux | grep kvm | grep $NAME, | grep -v grep | awk '{print $2}')
                    if [ $PID -gt 0 ]; then
                            DATA=$(top -p $PID -n 1 -b | tail -1 | awk -- '{print $9" "$10}')
                    else
                            DATA=""
                    fi
            fi

            echo $ID" "$NAME" "$STATE" "$MEM" "$DATA
    done
fi
